package me.msoucy.ptures.desktop

import com.badlogic.gdx.Application
import com.badlogic.gdx.backends.lwjgl.LwjglApplication
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration
import me.msoucy.ptures.PTures

object DesktopLauncher {
    @JvmStatic
    fun main(arg: Array<String>) {
        val config = LwjglApplicationConfiguration().apply {
            title = "Drop"
            width = 800
            height = 480
        }
        LwjglApplication(PTures(), config).logLevel = Application.LOG_DEBUG
    }
}
